### ISSUE TITLE
param lists

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ProbModelSEED#15]
I'm following this spec (which may not be correct) to create html templates.  https://github.com/olsonanl/app_service/blob/master/app_specs/FluxBalanceAnalysis.json

Are `media_supplement`, `rxnko`, and `geneko` truly strings?  If so, could they be changed to lists at some point?

**Comment by cshenry** [comment]
No, they are arrays. See allow_multiple=true.

**Comment by nconrad** [comment]
ahh, my bad.    Ok, adding fba tables now to see if this all works.
