### ISSUE TITLE
compartments in reaction/compound names

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ProbModelSEED#21]
This is not critical.  I noticed that there are compartments in the reaction and compound names.  Just wondering if those are really needed? 

Example: "Isoheptadecanoyllipoteichoic acid (n=24), linked, glucose substituted_c0"

**Comment by chian** [comment]
Nope. Guess there were a few compartment strippings that were missed.

**Comment by cshenry** [comment]
No, these are added automatically to compound names in models so that compounds will have unique names. Otherwise, if the same compound appears in multiple compartments, it will have identical names.
This prevents us from being able to use names as a lookup� which I think is not good.

**Comment by chian** [comment]
Ah, so these are in the models and not in the biochemistry then. Would make sense.

**Comment by mmundy42** [comment]
When I look at a model on the website, the name in the Reactions table and the Compounds table has the compartment suffix removed which I think is the right way to display it.  Are you stripping the suffix from the data returned by the modeling service?  Are there other places where the suffix should be removed?

**Comment by mmundy42** [comment]
Is there anything else we need to do here?  @cshenry commented that a compartment suffix that prevents us from using names as a lookup is not good.  But is that something we want to change?

**Comment by nconrad** [comment]
No further action.  I was trying to understand why.
