### ISSUE TITLE
Reconstruction failing for particular genome

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ProbModelSEED#25]
This may be related to the other failing jobs, not sure.   I reconstructed "Bacillus amyloliquefaciens subsp. plantarum” on complete media and it failed the error below.   The app service job id was 829a6e2f-aedc-4348-b40e-d025f8a03372.

keys on reference is experimental at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 905.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3097.
Use of uninitialized value in concatenation (.) or string at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3098.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3099.
Use of uninitialized value in concatenation (.) or string at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3100.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3101.
Use of uninitialized value in concatenation (.) or string at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3102.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3108.
Use of uninitialized value in addition (+) at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3151.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3152.
Use of uninitialized value in addition (+) at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3153.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3154.
Use of uninitialized value in addition (+) at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3155.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3156.
Use of uninitialized value in addition (+) at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3157.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3158.
Use of uninitialized value in addition (+) at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3159.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3160.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3182.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3192.
Use of uninitialized value in split at /disks/p3/deployment/lib/Bio/KBase/ObjectAPI/KBaseFBA/FBA.pm line 3199.
...

**Comment by mmundy42** [comment]
I ran model reconstruction using genome PATRICSOLR:1054400.5 and it completed successfully using the server at https://p3.theseed.org/services/ProbModelSEED around 3:15 pm today.

**Comment by nconrad** [comment]
It works for me now as well.
