### ISSUE TITLE
PATRICStore cache is not limited in size

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ProbModelSEED#29]
It looks like the cache in the PATRICStore object is allowed to grow to unlimited size.  This isn't a problem when running as an app since everything goes away when the app ends.  But when running in the server, the cache could grow quite large.  For example, the get_model() method proposed in issue #22 will need to get model objects from the workspace.  When lots of model objects are cached, the memory usage of the server could get out of control.

**Comment by mmundy42** [comment]
And it also looks like every object is stored twice in the cache.  When an object is first added to the cache, the key that is used is the object's UUID.  After the object is transformed or converted from JSON, the object is added again to the cache using the reference (workspace path) as the key.  If the cache needs to support lookups by both reference and UUID there should be a way to keep just one copy of the object.

**Comment by cshenry** [comment]
1.) PATRICStore is kept in �ProbModelSEEDHelper�, which is stored in the call context object, meaning it is deleted with every call. So the cache will never grow for longer than one call� unless this feature isn�t working right. note, you won�t see this behavior in �server� tests as the context object is recycled between calls (we probably should not do that by the way).

2.) I think only the �hash ref� is stored in both places. The data should only be stored once. When I make that assignment in the code, I�m assigning the ref, not the data. Are you seeing evidence to the contrary?

**Comment by cshenry** [comment]
See here:

sub helper {
	my ($self) = @_;
	if (!defined($CallContext->{_helper})) {
		$CallContext->{_helper} = Bio::ModelSEED::ProbModelSEED::ProbModelSEEDHelper->new({
			token => $self->token(),
			username => $self->user_id(),
			fbajobcache => $self->config()->{fbajobcache},
    		fbajobdir => $self->config()->{fbajobdir},
    		mfatoolkitbin => $self->config()->{mfatoolkitbin},
			logfile => $self->config()->{logfile},
			data_api_url => $self->config()->{data_api_url},
			"workspace-url" => $self->workspace_url(),
			"shock-url" => $self->config()->{shock_url},
			adminmode => $self->adminmode(),
			method => $self->current_method()
		});
	}
	return $CallContext->{_helper};
}

This is the helper function in ProbModelSEEDImpl.

**Comment by mmundy42** [comment]
1. I was a little confused by the Perl implementation of the server.  In Python servers, the context is passed as a parameter to each server method and not stored globally.  Just to make sure I understand, each client request causes a new context object to be created at https://github.com/ModelSEED/ProbModelSEED/blob/master/lib/Bio/ModelSEED/ProbModelSEED/Service.pm#L245.  And then this assignment makes the context object available to the server method https://github.com/ModelSEED/ProbModelSEED/blob/master/lib/Bio/ModelSEED/ProbModelSEED/Service.pm#L287.  So the cache is only valid for the life of the ProbModelSEEDHelper instantiation (which is either a client request to the server or an app).

2. This is the line that confused me: https://github.com/ModelSEED/ProbModelSEED/blob/master/lib/Bio/KBase/ObjectAPI/PATRICStore.pm#L169.  Which doesn't seem all that different from the first assignment at https://github.com/ModelSEED/ProbModelSEED/blob/master/lib/Bio/KBase/ObjectAPI/PATRICStore.pm#L146.

So line 146 makes a copy of objdatas but line 169 is using a reference?

**Comment by mmundy42** [comment]
As discussed at 6/29 meeting, there is a new PATRICStore for each client request.  So while objects are not removed from the cache, the scope of the PATRICStore is just for that request.  All objects are cached but the number of objects in the cache for a request is small.

In addition, the cache is being adjusted so that large, unchanging objects like the biochemistry and model templates will be cached once in the server.
