### ISSUE TITLE
Array values in addReactionFromHash() and addCompoundFromHash()

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ProbModelSEED#38]
In Bio::KBase::ObjectAPI::KBaseBiochem::Biochemistry there are addReactionFromHash() and addCompoundFromHash() methods for adding a single reaction or compound from an input hash.  Several of the elements in the hash are arrays which I don't understand.  In addReactionFromHash(), names, id, direction, deltag, and deltagerr are arrays of values.  In addCompoundFromHash(), names, id, mergeto, formula, unchargedFormula, mass, charge, deltag, are deltagerr are arrays of values.  Why are those elements arrays when adding a single reaction or compound?

**Comment by samseaver** [comment]
This is archaic by ModelSEED standards, these functions hark back to a time when the API was for loading flat-files and every cell was treated as an array reference. For some fields, this was appropriate, and for others, the code would simply call the first entry in the array.

**Comment by mmundy42** [comment]
Fixed by PR #44.
