### ISSUE TITLE
list_models and list_fba_studies could use meta data.

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ProbModelSEED#4]
This may already be in the plans, not sure.  Right now these methods return a list of references.  It would be great if these calls returned more info on the models and fba studies, similar to this page: http://coremodels.mcs.anl.gov/app/#/models/  (click on a model to see the associated fba studies)

So for models, this would be a list of objects, something like:
```
{
  orgName: "Ecoli",
  ref: "workspace/path/to/file",
  rxnCount: 100,
  cpdCount: 100
}
```

For FBAs, this would be a list of objects, something like:
```
{
  mediaRef: "media/ref/path",
  media: "media name",  // if needed? (if the name is different than the ref name?)
  objective: (objective_value === '10000000' ? 0 : objective_value),  // note this is an issue in KBase
  rxnCount: 50,
  cpdCount: 50,
  maximized: true,
  biomass: "Max ATP"
}
```

**Comment by cshenry** [comment]
YEah, it was always my intention to do something to this effect.

**Comment by nconrad** [comment]
Cool. I see this is returned by list_fba_studies.  My apologies in advance if it hasn't been updated at all.

```
"{
  "fba.2": {
    "objective_function": null,
    "rundate": "2015-06-03T18:31:19",
    "media": "/chenry/public/modelsupport/media/Complete",
    "fba": "/nconrad@patricbrc.org/home/models/.testgenome1.genome_model/fba/fba.2",
    "id": "fba.2",
    "objective": 0
  },
  "fba.0": {
    "objective_function": null,
    "rundate": "2015-06-03T17:40:58",
    "media": "/chenry/public/modelsupport/media/Complete",
    "fba": "/nconrad@patricbrc.org/home/models/.testgenome1.genome_model/fba/fba.0",
    "id": "fba.0",
    "objective": 0
  },
  "fba.1": {
    "objective_function": null,
    "rundate": "2015-06-03T17:43:10",
    "media": "/chenry/public/modelsupport/media/Complete",
    "fba": "/nconrad@patricbrc.org/home/models/.testgenome1.genome_model/fba/fba.1",
    "id": "fba.1",
    "objective": 0
  }
}"
```
Could we have this info as a list of objects instead?  Preferably ordered by most recent by default? 

Thanks!

**Comment by mmundy42** [comment]
Created pull request #13 with the change to return a sorted array.

**Comment by mmundy42** [comment]
We still haven't gotten to the original request in this issue.  

Neal, for list_fba_studies(), is there additional metadata you would like returned to improve the UX?

Chris, what is the objective_function key in the current metadata?  I don't see it in the FBA object itself.

**Comment by nconrad** [comment]
@mmundy42 , no, I don't think anything else is needed.  

I was thinking that the workspace path keys should be consistent for these.  Right now, that is `fba` for an fba object and `gapfill` for a gapfill object.  Can we call them the same thing?  Either `ref` or `path`?  I've been using `path` myself to avoid confusion with the UIDs, but I don't feel too strongly.

**Comment by mmundy42** [comment]
I think 'ref' would be the better choice to match what is already returned by list_models().  So 'ref' is used for an object's reference to itself and XXX_ref is is used for a reference to an object of type XXX.

**Comment by nconrad** [comment]
This makes more sense to me.  It isn't critical of course.

**Comment by nconrad** [comment]
oh, so the thing is that we (or I, anyway) don't use the UUIDs yet... but may want to?    "ref" may be the word to use there.  That's what I was thinking there.

**Comment by mmundy42** [comment]
In the spec file, a ref is defined as:

    /* Reference to location in PATRIC workspace (e.g. /home/chenry/models/MyModel)*/
    typedef string ref;
    
So I think a UUID should be referred to by another name.  In the ObjectMeta tuple it is called an 'ObjectID'

	ObjectID - a globally unique UUID assigned to every object that will never change even if the object is moved

**Comment by nconrad** [comment]
ok, cool.   I'd vote for 'id', 'uuid', 'sha' or similar.

**Comment by nconrad** [comment]
... and stop using "id" for things that are actually "names".
