### ISSUE TITLE
Need complete media data

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ProbModelSEED#56]
I reported this in kbase too.  No data is returned for /chenry/public/modelsupport/media/Complete.  It's particulaly confusing since complete media is the default.

<img width="1242" alt="screen shot 2015-07-24 at 4 30 33 pm" src="https://cloud.githubusercontent.com/assets/1194246/8885048/c6b80cee-3221-11e5-9d6b-5574c9411eb4.png">

**Comment by janakagithub** [comment]
What should go here is an explanation about "complete" media and how its relevant to the models. Complete media is not defined and an arbitrary medium, so there is no cpds to list.

**Comment by nconrad** [comment]
Thanks, @janakagithub.  Could you provide some text?  I'll help edit.

**Comment by nconrad** [comment]
I'll use what I just found on kbase (which you may have written?).  Are we able to give the resulting media compounds, though?

"Modeling growth in complete media means that the model is allowed to consume any nutrient for which a transport reaction is available to the model. For this reason, the content of complete media can change depending on which transport reactions are present in the model."

**Comment by janakagithub** [comment]
Not sure it is my wording.. I should say.. 
Complete media contains every compound for which a transporter exists in our database

**Comment by samseaver** [comment]
Right, so Janaka's definition is correct, but it means that if the gapfilling is done on complete media, then any of the transport reactions in the database will be added to the model in order for growth to occur. By this action, then the wording Neal found makes sense in that the nutrients in the complete media that are actually utilized will vary from model to model depending on the transporters that were added to the model. This is different from other defined medias in that one generally expects all/most nutrients within that media to be utilized, whilst a much smaller fraction of the complete media would be utilized.

**Comment by mmundy42** [comment]
@nconrad, do you have what you need for describing complete media?
