### ISSUE TITLE
media_ref disappeared

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ProbModelSEED#57]
I'm liking the new keys in list_fbas and list_gapfills, but it looks like when I unintegrated a gapfill solution, the `media_ref` is removed.
```
[
    {
        "integrated_solution": -1,
        "rundate": "2015-07-24T21:09:57",
        "solution_reactions": [],
        "media_ref": null,
        "ref": "/nconrad@patricbrc.org/home/models/.435.3_model/gapfilling/gf.1",
        "integrated": 0,
        "id": "gf.1"
    },
    {
        "integrated_solution": 0,
        "rundate": "2015-07-24T19:05:16",
        "solution_reactions": [ ... ],
        "media_ref": "/chenry/public/modelsupport/patric-media/Complete",
        "ref": "/nconrad@patricbrc.org/home/models/.435.3_model/gapfilling/gf.0",
        "integrated": 1,
        "id": "gf.0"
    }
]
```

**Comment by nconrad** [comment]
I'm not sure what's the difference between `integrated_solution` and `integrated` is.  I was using `integrated` before.  It looks like may 0 and -1 are being for `integrated_solution?

**Comment by mmundy42** [comment]
`integrated` is a boolean that indicates if the gap fill is integrated in the model.  It is turned on and off by "i" and "u" commands in manage_gapfill_solutions.

`integrated_solution` is the index number of a solution that is integrated.  Note that the first gapfill is not integrated so `integrated_solution` is -1 and the second gapfill with index 0 (gf.0) is integrated so `integrated_solution` is 0.  Not sure if that value is all the useful for the UI.

Still taking a look at why the media ref disappeared.

**Comment by mmundy42** [comment]
@nconrad, do you also need the `solution_reactions` to be preserved when unintegrating/integrating solutions?

The field names in the output returned by manage_gapfill_solutions() and list_gapfill_solutions() are different than the field names for the user metadata in the gapfill object and that is why they are getting lost.

**Comment by nconrad** [comment]
sorry, I haven't checked solution_reactions yet.  But, yeah, it seems like that solution_reactions should be preserved?  My understanding is that users want to produce solutions and switch between various solution via "integrating".  So, it seems like viewing the results should be separate from integration?  However, returning solution_reactions won't scale well performance-wise when there are a lot of gapfill solutions.... but I think it should be safe to address that later on?
