### ISSUE TITLE
Reaction status lost when running Update_Reaction_Status multiple times

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ProbModelSEED#83]
I accidentally ran Update_Reaction_Status.pl twice in a row and noticed that the status value changed even though no updates were made to the reaction.  For example, here are the relevant fields for rxn00001 after running Update_Reaction_Status the first time:

``` 
code: (1) cpd00001[0] + (1) cpd00012[0] <=> (2) cpd00009[0]
stoichiometry: -1:cpd00001:0:0:"H2O";-1:cpd00012:0:0:"PPi";2:cpd00009:0:0:"Phosphate";1:cpd00067:0:0:"H+"
equation: (1) cpd00001[0] + (1) cpd00012[0] <=> (2) cpd00009[0] + (1) cpd00067[0]
status: OK|HB
```

And if you run Update_Reaction_Status again, the status field is reset to "OK" because no changes were required to mass and charge balance the reaction:

```
code: (1) cpd00001[0] + (1) cpd00012[0] <=> (2) cpd00009[0]
stoichiometry:-1:cpd00001:0:0:"H2O";-1:cpd00012:0:0:"PPi";2:cpd00009:0:0:"Phosphate";1:cpd00067:0:0:"H+"
equation: (1) cpd00001[0] + (1) cpd00012[0] <=> (2) cpd00009[0] + (1) cpd00067[0]
status: OK
```

The status should not be lost when checking the reaction again.  Fixing requires an update to the checkReactionMassChargeBalance() method in a Reaction object to start with the current status and an update to the Update_Reaction_Status script to set the status in the temporary Reaction object to the current value.

**Comment by samseaver** [comment]
This is an exception, simply because only protons are ever modified, so I can update the function to say keep old status of "OK|HB" if new status is "OK".

**Comment by samseaver** [comment]
OK, so I was working on this, but I got myself really muddled up because after I merged in your latest changes, I started to realize that I should've been using the ProbModelSEED dev branch for the underlying API and not the KBaseFBAModeling dev branch which I'd been using by default.

To cap it, though I feel like I made the right switch, I'm getting different status messages in the reactions.master.tsv.  @mmundy42 : Can you check my latest iteration of the reactions.master.tsv file, and see if it matches what you have locally? I may have to revert my commits otherwise.

**Comment by samseaver** [comment]
OK, look, I decided to start over, I did a hard reset to https://github.com/ModelSEED/ModelSEEDDatabase/commit/9a079ceb91d835e943256765a18fda8d4547def0 and I switched to using the ObjectAPI in ProbModelSEED's dev branch, like we agreed over email.

Now, if I do this:
```
./Print_Master_Reactions_List.pl
./Update_Reaction_Status.pl
```

I get like 4K+ reactions with a modified status. Ideally, of course, we'd both want to be able to run those commands without statuses being modified.  But the results are a bit of a mess:

```
git diff ../Biochemistry/reactions.master.tsv | grep ^[-+] | cut -f1,18
-rxn04386       OK
+rxn04386       OK|HB
-rxn05120       OK
+rxn05120       OK|HB
-rxn05295       MI:C:-28.1676/H:-34.6301/N:-11.6231/O:-20.4327/P:-2.9386|CI:10000000
+rxn05295       CPDFORMERROR
-rxn05701       OK
+rxn05701       CPDFORMERROR
-rxn05765       MI:C:-34/H:-28/O:-14|CI:20000000
-rxn05766       MI:C:-34/H:-28/O:-14|CI:20000000
+rxn05765       CPDFORMERROR
+rxn05766       CPDFORMERROR
-rxn05773       HB|CI:2
+rxn05773       CPDFORMERROR
-rxn05775       HB|CI:2
+rxn05775       CPDFORMERROR
```

et cetera. Can you confirm that if you re-run the scripts, using the ProbModelSEED API as described, that you don't get any changes in your reactions.master.tsv file?

**Comment by mmundy42** [comment]
Making some progress.  It looks like the status values have changed over time so that you need to run Update_Reaction_Status.pl with the reaction status unset in the temporary Reaction object the first time after running Print_Master_Reactions_List.pl.  That normalizes the reaction status to the current format.

After running Update_Reaction_Status.pl, the first time 8,570 reactions had their status updated.  Checking the status with Validate_Reactions.py there are:

Reactions with OK status: 19,879
Reactions with OK status after balancing: 2,526
Reactions with bad status: 12,296

If you run Update_Reaction_Status.pl again you will still get updates because the checkReactionMassChargeBalance() method doesn't pay attention to the current status.  I fixed that but there is still something going with charge imbalance.  It is being added again every time you run Update_Reaction_Status.pl.  For example, rxn00059 has status `CI:4` with gets updated to `CI:-4|CI:-4` on the second update.

I pushed my changes to Update_Reaction_Status.pl and checkReactionMassChargeBalance() and will keep debugging.

**Comment by samseaver** [comment]
No let me do the reaction status update, I spent some time on it last night, but I wanted to be able to run Update_Reaction_Status.pl *without* any changes from what was already stored in the GitHub repository.  Can you push the changes you made to the compounds.mods.tsv and then let me figure out the second update problem.

**Comment by mmundy42** [comment]
All of my updates are pushed.  I haven't been able to get it to run without any changes because even after running Update_Reaction_Status.pl just one time there are reactions with different status values. Maybe there is a difference between the ModelSEED code and KBase code? 

If I run the following:

```
./Print_Master_Reactions_List.pl
./Update_Reaction_Status.pl --reset
./Update_Reaction_Status.pl
```

the second run of Update_Reaction_Status.pl still finds charge and mass imbalanced reactions.  The mass imbalance is reported once because of https://github.com/ModelSEED/ProbModelSEED/blob/dev/lib/Bio/KBase/ObjectAPI/KBaseBiochem/Reaction.pm#L1139.  The charge imbalance is duplicated because of https://github.com/ModelSEED/ProbModelSEED/blob/dev/lib/Bio/KBase/ObjectAPI/KBaseBiochem/Reaction.pm#L1144.

**Comment by samseaver** [comment]
OK, let's back up.  At some point, we said we would switch to the ProbModelSEED dev branch, so, when you made this commit:

https://github.com/ModelSEED/ModelSEEDDatabase/commit/9a079ceb91d835e943256765a18fda8d4547def0

were you using the ProbModelSEED dev branch?

**Comment by samseaver** [comment]
I'll do that, and next time you make a major change to an established
script, you at least leave a long message in the commit itself describing
it.  I read all the emails I get from GitHub about commits, but I'd been
too busy recently to go and check the diffs.

GitHub isn't responding at the moment, parts of the server is under a
suspected DDOS attack
S


On Mon, Aug 24, 2015 at 3:25 PM, Mike Mundy <notifications@github.com>
wrote:

> All of my updates are pushed. I haven't been able to get it to run without
> any changes because even after running Update_Reaction_Status.pl just one
> time there are reactions with different status values. Maybe there is a
> difference between the ModelSEED code and KBase code?
>
> If I run the following:
>
> ./Print_Master_Reactions_List.pl
> ./Update_Reaction_Status.pl --reset
> ./Update_Reaction_Status.pl
>
> the second run of Update_Reaction_Status.pl still finds charge and mass
> imbalanced reactions. The mass imbalance is reported once because of
> https://github.com/ModelSEED/ProbModelSEED/blob/dev/lib/Bio/KBase/ObjectAPI/KBaseBiochem/Reaction.pm#L1139.
> The charge imbalance is duplicated because of
> https://github.com/ModelSEED/ProbModelSEED/blob/dev/lib/Bio/KBase/ObjectAPI/KBaseBiochem/Reaction.pm#L1144
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModelSEED/ProbModelSEED/issues/83#issuecomment-134367116>
> .
>



-- 
Asst. Computational Scientist
Mathematics and Computer Science Division
Biosciences Division
Argonne National Laboratory
9700 S. Cass Avenue
Argonne, IL 60439

http://www.linkedin.com/pub/sam-seaver/0/412/168
samseaver@gmail.com
(773) 796-7144

"We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time."
   --T. S. Eliot

**Comment by samseaver** [comment]
OK, so, the situation is normalized, and, based on this commit, you should no longer get this particular problem:

https://github.com/ModelSEED/ModelSEEDDatabase/commit/d776bff0dc0af0a48605cf8de01ac7ccebb4ce90

However, as discussed via email, there is a separate problem with compartment sorting in the equation, so if you re-run this script, you'll still get a few equations that are "flipped". It's actually unavoidable until we migrate to using the master files properly (i.e. away from the original compartment alphabet and to the new compartment numerals)
