### ISSUE TITLE
Need user's rast annotated genomes

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ProbModelSEED#87]

**Comment by nconrad** [comment]
I can help in any way.

**Comment by cshenry** [comment]
This is now done. Here is the spec for the new function:
/* RAST job data
		
		string owner - owner of the job
		string project - project name
		string id - ID of the job
		string creation_time - time of creation
		string mod_time - time of modification
		int genome_size - size of genome
		int contig_count - number of contigs
		string genome_id - ID of the genome created by the job
		string genome_name - name of genome
		string type - type of job

	*/
	typedef structure {
		string owner;
		string project;
		string id;
		string creation_time;
		string mod_time;
		int genome_size;
		int contig_count;
		string genome_id;
		string genome_name;
		string type;
    } RASTJob;
/* Output for the "list_rast_jobs_params" function.
	
		string owner - user for whom jobs should be listed (optional - default is authenticated user)
		
	*/
	typedef structure {
		string owner;
    } list_rast_jobs_params;
    /*
        Retrieves a list of jobs owned by the specified RAST user
    */
    funcdef list_rast_jobs(list_rast_jobs_params input) returns (list<RASTJob> output)  authentication required;

It returns the jobs of the logged user if you do not specify the owner. It will not return jobs of other users unless you are an admin.

**Comment by cshenry** [comment]
Here's the javascript client:
https://github.com/ModelSEED/MSSeedSupportServer/tree/master/lib/javascript/MSSeedSupportServer

**Comment by cshenry** [comment]
This is the server URL:
http://bio-data-1.mcs.anl.gov/services/ms_fba

**Comment by cshenry** [comment]
Let me know if you need any additional info, but this should work for you.

**Comment by nconrad** [comment]
Hey @cshenry, I'm getting the following error.  Sounds like we just need to change "Access-Control-Allow-Origin" to "*", that should cover "localhost".

XMLHttpRequest cannot load http://bio-data-1.mcs.anl.gov/services/ms_fba. The 'Access-Control-Allow-Origin' header contains multiple values '*, http://localhost', but only one is allowed. Origin 'http://localhost' is therefore not allowed access.

Request: {"version":"1.1","method":"MSSeedSupportServer.list_rast_jobs","id":"037619781447574496","params":[{}]}:

**Comment by danielolson5** [comment]
I think I've corrected this.  Can you test and let me know???

**Comment by nconrad** [comment]
Now I get "XMLHttpRequest cannot load http://bio-data-1.mcs.anl.gov/services/ms_fba. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://140.221.67.62' is therefore not allowed access."

In theory, when it works, I'll get a green box at http://140.221.67.62/#/about/ :)

**Comment by danielolson5** [comment]
Looks like there's a header there:
curl -H "Origin: http://140.221.67.62" --verbose http://bio-data-1.mcs.anl.gov/services/ms_fba
* About to connect() to bio-data-1.mcs.anl.gov port 80
*   Trying 192.5.200.103... * connected
* Connected to bio-data-1.mcs.anl.gov (192.5.200.103) port 80
> GET /services/ms_fba HTTP/1.1
User-Agent: curl/7.13.1 (i686-apple-darwin13.0.0) libcurl/7.13.1 OpenSSL/0.9.8o zlib/1.2.5 libidn/1.19
Host: bio-data-1.mcs.anl.gov
Pragma: no-cache
Accept: */*
Origin: http://140.221.67.62

< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.6.2
< Date: Thu, 10 Sep 2015 20:23:53 GMT
< Content-Type: application/json
< Content-Length: 120
< Connection: keep-alive
< Access-Control-Allow-Origin: *
* Connection #0 to host bio-data-1.mcs.anl.gov left intact
* Closing connection #0
{"version":"1.1","error":{"name":"JSONRPCError","code":-32300,"message":"HTTP GET not allowed."},"id":"433545587289526"}

**Comment by nconrad** [comment]
yeah, the CORs issue is fixed now.  Thanks, @danielolson5 .    I'll test the actual command a little later.

**Comment by nconrad** [comment]
@cshenry, you are probably already aware... For awhile, list_rast_jobs was working occasionally (with the following error occurring sometimes), but it looks the following is always returned for my token now.

{"version":"1.1","error":{"error":"ERROR{Username not found!}ERROR\n\nTrace begun at /vol/model-prod/kbase/deploy/../MSSeedSupportServer/lib/Bio/ModelSEED/MSSeedSupportServer/MSSeedSupportImpl.pm line 171\nBio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl::_error('Bio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl=HASH(0x702df60)', 'Username not found!') called at /vol/model-prod/kbase/deploy/../MSSeedSupportServer/lib/Bio/ModelSEED/MSSeedSupportServer/MSSeedSupportImpl.pm line 180\nBio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl::get_user_object('Bio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl=HASH(0x702df60)', 'login', 'nconrad') called at /vol/model-prod/kbase/deploy/../MSSeedSupportServer/lib/Bio/ModelSEED/MSSeedSupportServer/MSSeedSupportImpl.pm line 1423\nBio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl::list_rast_jobs('Bio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl=HASH(0x702df60)', 'HASH(0x87593d0)') called at /vol/model-prod/kbase/deploy/../MSSeedSupportServer/lib/Bio/ModelSEED/MSSeedSupportServer/Server.pm line 310\neval {...} at /vol/model-prod/kbase/deploy/../MSSeedSupportServer/lib/Bio/ModelSEED/MSSeedSupportServer/Server.pm line 302\nBio::ModelSEED::MSSeedSupportServer::Server::call_method('Bio::ModelSEED::MSSeedSupportServer::Server=HASH(0x70442b0)', 'HASH(0x8d4a0d8)', 'HASH(0x986e9c0)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/RPC/Any/Server.pm line 33\neval {...} at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/RPC/Any/Server.pm line 26\nRPC::Any::Server::handle_input('Bio::ModelSEED::MSSeedSupportServer::Server=HASH(0x70442b0)', 'HASH(0x8069220)') called at /vol/model-prod/kbase/deploy/bin/../../MSSeedSupportServer/lib/MSSeedSupportServer.psgi line 20\nPlack::Sandbox::_2fvol_2fmodel_2dprod_2fkbase_2fdeploy_2fbin_2f_2e_2e_2f_2e_2e_2fMSSeedSupportServer_2flib_2fMSSeedSupportServer_2epsgi::__ANON__('HASH(0x8069220)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Plack/Middleware/CrossOrigin.pm line 178\nPlack::Middleware::CrossOrigin::call('Plack::Middleware::CrossOrigin=HASH(0x7029a28)', 'HASH(0x8069220)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Plack/Component.pm line 39\nPlack::Component::__ANON__('HASH(0x8069220)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Plack/Util.pm line 165\neval {...} at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Plack/Util.pm line 165\nPlack::Util::run_app('CODE(0x7044250)', 'HASH(0x8069220)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Starman/Server.pm line 223\nStarman::Server::process_request('Starman::Server=HASH(0x446cfa8)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Net/Server.pm line 141\nNet::Server::run_client_connection('Starman::Server=HASH(0x446cfa8)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Net/Server/PreFork.pm line 273\neval {...} at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Net/Server/PreFork.pm line 273\nNet::Server::PreFork::run_child('Starman::Server=HASH(0x446cfa8)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Net/Server/PreFork.pm line 229\nNet::Server::PreFork::run_n_children('Starman::Server=HASH(0x446cfa8)', 1) called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Net/Server/PreFork.pm line 447\nNet::Server::PreFork::coordinate_children('Starman::Server=HASH(0x446cfa8)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Net/Server/PreFork.pm line 401\nNet::Server::PreFork::run_parent('Starman::Server=HASH(0x446cfa8)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Starman/Server.pm line 104\nStarman::Server::run_parent('Starman::Server=HASH(0x446cfa8)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Net/Server/PreFork.pm line 147\nNet::Server::PreFork::loop('Starman::Server=HASH(0x446cfa8)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Net/Server.pm line 116\nNet::Server::run('Starman::Server=HASH(0x446cfa8)', 'port', 'ARRAY(0x489a778)', 'host', 'ARRAY(0x489a7d8)', 'proto', 'ARRAY(0x489a838)', 'serialize', 'flock', 'log_level', 2, 'min_servers', 5, 'min_spare_servers', 4, 'max_spare_servers', 4, 'max_servers', 5, 'max_requests', 20, 'user', 4275, 'group', '311 311 1043 1048 1049 1050 3025 3262', 'listen', 1024, 'leave_children_open_on_hup', 1, 'no_client_stdout', 1, 'pid_file', '/vol/model-prod/kbase/deploy/bin/../pids/mss-service.pid') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Starman/Server.pm line 61\nStarman::Server::run('Starman::Server=HASH(0x446cfa8)', 'CODE(0x446d098)', 'HASH(0x446d458)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Plack/Handler/Starman.pm line 18\nPlack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x446cfd8)', 'CODE(0x446d098)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Plack/Loader/Delayed.pm line 20\nPlack::Loader::Delayed::run('Plack::Loader::Delayed=HASH(0x43b0728)', 'Plack::Handler::Starman=HASH(0x446cfd8)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/lib/perl5/site_perl/5.12.2/Plack/Runner.pm line 263\nPlack::Runner::run('Plack::Runner=HASH(0x443bfd8)') called at /vol/rast-bcr/2010-1124/linux-rhel5-x86_64/bin/starman line 31\n","name":"JSONRPCError","code":-32603,"message":"ERROR{Username not found!}ERROR\n\nTrace begun at /vol/model-prod/kbase/deploy/../MSSeedSupportServer/lib/Bio/ModelSEED/MSSeedSupportServer/MSSeedSupportImpl.pm line 171\nBio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl::_error('Bio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl=HASH(0x702df60)', 'Username not found!') called at /vol/model-prod/kbase/deploy/../MSSeedSupportServer/lib/Bio/ModelSEED/MSSeedSupportServer/MSSeedSupportImpl.pm line 180\nBio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl::get_user_object('Bio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl=HASH(0x702df60)', 'login', 'nconrad') called at /vol/model-prod/kbase/deploy/../MSSeedSupportServer/lib/Bio/ModelSEED/MSSeedSupportServer/MSSeedSupportImpl.pm line 1423\nBio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl::list_rast_jobs('Bio::ModelSEED::MSSeedSupportServer::MSSeedSupportImpl=HASH(0x702df60)', 'HASH(0x87593d0)') called at /vol/model- ...

**Comment by nconrad** [comment]
This is looking good now.  I haven't seen any issues lately.
